version: '3.1'

services:
  db:
    image: mongo:5
    command: --serviceExecutor adaptive
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABASE: nest-movie-app
    volumes:
      - ./mongo:/data/db
